#!/usr/bin/bash
n=1
while [ $n -le 10 ]
do
        if [[ $n -eq 9 ]]
        then
                echo "Best School"
                echo "Hi"
        else
                echo "Best School"
fi
        ((n++))
done
